spring.application.name=hexagonal

# Configuración de la base de datos H2 en memoria
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:hexagonaldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Le decimos a JPA que use H2 y que cree/actualice las tablas automáticamente.
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update